apiVersion: v1
kind: Service
metadata:
  name: {{ include "argo-rollout-demo.fullname.preview" . }}
  labels:
    {{- include "argo-rollout-demo.labels.preview" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "argo-rollout-demo.selectorLabels.preview" . | nindent 4 }}
