apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: argo-rollouts
  includeCRDs: true
  version: 2.5.0
  repo: 'https://argoproj.github.io/argo-helm'
  namespace: argocd
  releaseName: argo-rollouts
