# Default values for argo-rollout.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 4

image:
  repository: argoproj/rollouts-demo
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: red

service:
  type: ClusterIP
  port: 80

ingressCanary:
  enabled: true
  className: ""
  annotations:
    ingress.kubernetes.io/proxy-body-size: 100M
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/app-root: /
  hosts:
    - host: preview.demo.io
      paths:
        - path: /
          pathType: ImplementationSpecific

ingress:
  enabled: false
  className: ""
  annotations:
    ingress.kubernetes.io/proxy-body-size: 100M
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/app-root: /
  hosts:
    - host: stable.demo.io
      paths:
        - path: /
          pathType: ImplementationSpecific

resources:
   limits:
     memory: 32Mi
     cpu: 5m
   requests:
     memory: 32Mi
     cpu: 5m

rollout:
  canary:
    maxSurge: "50%"
    dynamicStableScale: true
    analysis:
      args:
      - name: ingress
        value: argo-rollout
    steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 40
      - pause: { duration: 10 }
      - setWeight: 60
      - pause: { duration: 10 }
      - setWeight: 80
      - pause: { duration: 10 }
