apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollout-demo
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  project: default
  source:
    repoURL: https://github.com/mifonpe/argocd-gitops-demo
    targetRevision: main 
    path: argocd/values/argo-rollout-demo
  destination:
    server: https://kubernetes.default.svc
    namespace: default
